<a href="https://colab.research.google.com/github/anastasiashapoval/machine-learning/blob/main/%D1%88%D0%B0%D0%BF%D0%BE%D0%B2%D0%B0%D0%BB_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# Варіант 19
# одновимірні - а, двохвимірні - m
import numpy as np

In [9]:
# 1. Створіть одновимірний масив (вектор) з добутками парних чисел на їхні попередні
# непарні числа, починаючи з 2, та виведіть його значення.

even_numbers = np.arange(2, 21, 2)

a1 = even_numbers * (even_numbers - 1)

print(a1)

[  2  12  30  56  90 132 182 240 306 380]


In [13]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
# квадратів випадкових цілих чисел від 1 до 100.
m1 = np.random.randint(1, 101, (3, 3))

m2 = np.square(m1)

print(m2)

[[7225  576 3481]
 [2401 5476  900]
 [2601 1369 6561]]


In [16]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від -2 до
# 2 та знайдіть середнє за модулем значення його елементів
m3 = np.random.uniform(-2, 2, (5, 5))

m4 = np.mean(np.abs(m3))

print("Матриця:")
print(m3)
print("Середнє за модулем значення елементів:", m4)

Матриця:
[[-0.02423977  1.08323214  1.19764533 -1.37163489 -1.79698113]
 [-0.62215566 -0.00450756 -1.50310023  0.24341298 -1.65637314]
 [ 0.15913216 -1.08966768  0.01041421 -0.3351671   1.54863676]
 [-1.31056132 -1.5232852   1.55788884  0.44911573  1.37137627]
 [ 1.90116965  1.26555246  0.51999229 -0.83259672  1.44213492]]
Середнє за модулем значення елементів: 0.9927989655575828


In [20]:
# 4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення
m5 = np.random.rand(5, 5)

mean = np.mean(m5)

less_than_mean = m5[m5 < mean] # елементи, менші за середнє значення

m6 = np.sum(less_than_mean) # сума елементів, мннших за середнє значення

print("Масив:")
print(m5)
print("Середнє значення масиву:", mean)
print("Сума елементів, менших за середнє:", m6)

Масив:
[[0.05106069 0.57849893 0.51837234 0.44910222 0.74945248]
 [0.12123298 0.35964957 0.90956945 0.34635221 0.11132286]
 [0.07173635 0.76416813 0.05195512 0.37722908 0.66550553]
 [0.19258131 0.20733075 0.62362978 0.18946818 0.76097333]
 [0.18250167 0.34711698 0.30435428 0.80702536 0.82656707]]
Середнє значення масиву: 0.4226702660709879
Сума елементів, менших за середнє: 2.913892032607899


In [22]:
# 5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними
# числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання
# ta множення.

a2 = np.random.uniform(-2, 2, 7)
a3 = np.random.uniform(-2, 2, 7)

add = a2 + a3
subtract = a2 - a3
multiplicate = a2 * 3

print("Масив 1:", a2)
print("Масив 2:", a3)
print("Додавання:", add)
print("Віднімання:", subtract)
print("Множення:", multiplicate)

Масив 1: [-0.90975775 -1.81647901  0.48063086  0.97003988  1.5241198  -1.73382982
  0.53371466]
Масив 2: [ 0.36263135 -1.96515143 -0.64921587 -1.56273769  0.74413641 -1.00942377
 -1.10456476]
Додавання: [-0.5471264  -3.78163044 -0.16858501 -0.59269781  2.26825621 -2.74325359
 -0.57085011]
Віднімання: [-1.2723891   0.14867242  1.12984673  2.53277756  0.77998339 -0.72440605
  1.63827942]
Множення: [-2.72927325 -5.44943702  1.44189257  2.91011963  4.5723594  -5.20148946
  1.60114397]


In [ ]:
# 6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 7 до 17 та
# знайдіть їх добуток.

