<a href="https://colab.research.google.com/github/anastasiashapoval/machine-learning/blob/main/%D1%88%D0%B0%D0%BF%D0%BE%D0%B2%D0%B0%D0%BB_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Варіант 19
import numpy as np

In [7]:
# 1. Створіть одновимірний масив (вектор) з добутками парних чисел на їхні попередні
# непарні числа, починаючи з 2, та виведіть його значення.

even_numbers = np.arange(2, 21, 2)

array = even_numbers * (even_numbers - 1)

print(array)

[  2  12  30  56  90 132 182 240 306 380]


In [6]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
# квадратів випадкових цілих чисел від 1 до 100.
matrix1 = np.random.randint(1, 101, (3, 3))

matrix2 = np.square(matrix1)

print(matrix2)

[[2500 9604  841]
 [ 961 8100    1]
 [ 121 4225 8100]]


In [44]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від -2 до
# 2 та знайдіть середнє за модулем значення його елементів
matrix1 = np.random.uniform(-2, 2, (5, 5))

matrix2 = np.mean(np.abs(matrix1))

print(matrix1)
print("середнє за модулем значення елементів:", matrix2)

[[-1.02032591  0.74986505  0.29761484  1.19894433 -0.2977757 ]
 [-1.13888848  0.95605528  1.28849905  0.18527779  1.1662779 ]
 [ 0.9255117  -1.91081564 -1.87670134 -1.9210899  -0.21726653]
 [ 0.66429897  0.09613957 -1.40495146  1.9770101  -1.46852433]
 [ 0.25867761  0.52111422 -1.21822671 -0.19728623 -0.81666804]]
середнє за модулем значення елементів: 0.950952267508625


In [43]:
# 4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та обчисліть суму елементів, які менше середнього значення
matrix1 = np.random.rand(5, 5)

mean = np.mean(matrix1)

less_than_mean = matrix1[matrix1 < mean] # елементи, менші за середнє значення

matrix2 = np.sum(less_than_mean) # сума елементів, мннших за середнє значення

print(matrix1)
print("середнє значення масиву:", mean)
print("сума елементів, менших за середнє:", matrix2)

[[0.32692945 0.35815878 0.14579757 0.98544165 0.64707137]
 [0.1120854  0.57680584 0.20170737 0.8718585  0.67934653]
 [0.88982469 0.74851567 0.37074365 0.33271528 0.22939605]
 [0.31020524 0.57405494 0.19650749 0.85414217 0.52546103]
 [0.78801837 0.99888658 0.80922558 0.78568707 0.90677448]]
середнє значення масиву: 0.5690144309373846
сума елементів, менших за середнє: 3.1097073309184298


In [42]:
# 5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими дійсними
# числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання
# ta множення.

array1 = np.random.uniform(-2, 2, 7)
array2 = np.random.uniform(-2, 2, 7)

add = array1 + array2
sub = array1 - array2
multi = array1 * 3

print("масив 1:", array1)
print("масив 2:", array2)
print("додавання:", add)
print("віднімання:", sub)
print("множення:", multi)

масив 1: [-1.01049216  0.67377786  1.54612755 -0.75826036  1.81465317  1.24551272
 -1.77893655]
масив 2: [-1.41450088  1.78134191 -1.28649578 -1.94675311 -1.21250231  1.94226059
  0.13822722]
додавання: [-2.42499303  2.45511977  0.25963177 -2.70501347  0.60215085  3.18777331
 -1.64070933]
віднімання: [ 0.40400872 -1.10756404  2.83262332  1.18849275  3.02715548 -0.69674787
 -1.91716377]
множення: [-3.03147648  2.02133359  4.63838264 -2.27478108  5.4439595   3.73653817
 -5.33680964]


In [119]:
# 6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 7 до 17 та
# знайдіть їх добуток.

matrix1 = np.random.randint(7, 18, (4, 4))
matrix2 = np.random.randint(7, 18, (4, 4))

d = np.dot(matrix1, matrix2)

print("матриця 1:")
print(matrix1)
print("матриця 2:")
print(matrix2)
print("добуток матриць:")
print(d)

матриця 1:
[[16 17 12 15]
 [13 13 12 10]
 [12 11 12 11]
 [14 13 17 15]]
матриця 2:
[[16  9 15  9]
 [ 7 11 16 16]
 [10 12 15  8]
 [11 10 11 17]]
добуток матриць:
[[660 625 857 767]
 [529 504 693 591]
 [510 483 657 567]
 [650 623 838 725]]


In [118]:
# 7. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 6 та перемножте їх між собою.

matrix1 = np.random.randint(1, 7, (4, 2))

matrix2 = np.random.randint(1, 7, (2, 5))

d = np.dot(matrix1, matrix2)

print("матриця 1:")
print(matrix1)
print("матриця 2:")
print(matrix2)
print("добуток матриць:")
print(d)

матриця 1:
[[2 1]
 [5 5]
 [2 3]
 [3 1]]
матриця 2:
[[2 6 5 1 6]
 [1 2 4 6 3]]
добуток матриць:
[[ 5 14 14  8 15]
 [15 40 45 35 45]
 [ 7 18 22 20 21]
 [ 7 20 19  9 21]]


In [117]:
# 8.  Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
# від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 11, (2, 2))

inverse_matrix = np.linalg.inv(matrix)

print("матриця:")
print(matrix)
print("обернена матриця:")
print(inverse_matrix)

матриця:
[[ 4  5]
 [10  1]]
обернена матриця:
[[-0.02173913  0.10869565]
 [ 0.2173913  -0.08695652]]


In [116]:
# 9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від 10 до 50 та транспонуйте її.
matrix = np.random.uniform(10, 50, (3, 3))

t_matrix = matrix.T

print("матриця:")
print(matrix)
print("транспонована матриця:")
print(t_matrix)

матриця:
[[10.23192513 46.5961284  12.43068011]
 [13.41531007 25.91100792 30.45617065]
 [18.61777575 20.94395376 36.29250631]]
транспонована матриця:
[[10.23192513 13.41531007 18.61777575]
 [46.5961284  25.91100792 20.94395376]
 [12.43068011 30.45617065 36.29250631]]


In [115]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
# випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
# числами від 0 до 1, і знайдіть добуток матриці на вектор.
matrix = np.random.randint(1, 11, (3, 4))

vector = np.random.uniform(0, 1, (4, 1))

d = np.dot(matrix, vector)

print("матриця:")
print(matrix)
print("вектор:")
print(vector)
print("добуток:")
print(d)

матриця:
[[ 5  8  9  1]
 [ 4  8  1  3]
 [ 8  1 10  9]]
вектор:
[[0.29905026]
 [0.82347666]
 [0.64655288]
 [0.27020236]]
добуток:
[[14.17224287]
 [ 9.24117429]
 [12.11322879]]


In [114]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
# випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
# діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

matrix = np.random.uniform(0, 1, (2, 3))

vector = np.random.randint(1, 11, (3, 1))

d = np.dot(matrix, vector)

print("матриця:")
print(matrix)
print("вектор:")
print(vector)
print("добуток:")
print(d)

матриця:
[[0.39713717 0.48298931 0.79463979]
 [0.54168163 0.95033612 0.71260502]]
вектор:
[[6]
 [4]
 [7]]
добуток:
[[ 9.87725877]
 [12.03966944]]


In [113]:
# 12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 5 та знайдіть добуток елементів діагоналей обох матриць (окремо).

matrix1 = np.random.randint(1, 6, (3, 3))
matrix2 = np.random.randint(1, 6, (3, 3))

d_diag1 = np.prod(np.diag(matrix1))
d_diag2 = np.prod(np.diag(matrix2))

print(matrix1)
print("добуток елементів діагоналі першої матриці:", d_diag1)

print(matrix2)
print("добуток елементів діагоналі другої матриці:", d_diag2)

[[3 2 1]
 [5 5 2]
 [4 5 5]]
добуток елементів діагоналі першої матриці: 75
[[1 3 4]
 [3 1 2]
 [3 5 5]]
добуток елементів діагоналі другої матриці: 5


In [112]:
# 13. Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в
# діапазоні від -1 до 1 та знайдіть суму їх елементів.

matrix1 = np.random.uniform(-1, 1, (3, 3))
matrix2 = np.random.uniform(-1, 1, (3, 3))

sum1 = np.sum(matrix1)
sum2 = np.sum(matrix2)
sum3 = sum1 + sum2

print(matrix1)
print("сума елементів першої матриці:", sum1)

print(matrix2)
print("сума елементів другої матриці:", sum2)

print("сума всіх елементів:")
print(sum3)

[[-0.72663246 -0.44305981  0.64933379]
 [ 0.19953253 -0.4886203  -0.90238993]
 [ 0.12614196  0.2869429   0.90983363]]
сума елементів першої матриці: -0.3889176870737032
[[ 0.46263828 -0.87262599 -0.78496826]
 [ 0.59686213  0.11997767  0.56418115]
 [ 0.69114272 -0.38502099 -0.8283707 ]]
сума елементів другої матриці: -0.4361839863703618
сума всіх елементів:
-0.825101673444065


In [102]:
# 14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -3 до 3 та знайдіть найбільший елемент матриці.

matrix = np.random.uniform(-3, 3, (3, 3))

max = np.max(matrix)

print(matrix)
print("найбільший елемент:", max)

[[ 1.52791187 -2.47260553 -2.75257396]
 [-0.43316575 -0.26302473 -1.62755738]
 [ 1.52823876 -2.89942363  2.06445151]]
найбільший елемент: 2.06445150651299


In [101]:
# 15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить кількість нульових
# елементів в кожному рядку матриці.

matrix = np.random.uniform(-0.5, 0.5, (3, 3))

zero_vector = np.sum(matrix == 0, axis=1).reshape(-1, 1)

print(matrix)
print("кількість нульових елементів в кожному рядку:")
print(zero_vector)

[[ 0.23321091 -0.44285753  0.30952526]
 [-0.38557739  0.46658656 -0.48643274]
 [-0.36291051  0.14909419  0.24474728]]
кількість нульових елементів в кожному рядку:
[[0]
 [0]
 [0]]


In [ ]:
# Висновок: під час виконання даної лабораторної роботи була проведена робота з матрицями та векторами за допомогою бібліотеки NumPy, а саме
# заповнення випадковими дійсними та цілими числами, знаходження середнього значення, додавання, віднімання, множення (в тому числі і поелементне), транспонування, знаходження оберненої матриці, добутку елементів діагоналі тощо.